import type { Metadata } from "next";
import { ThemeProvider } from "@/components/common/theme-provider"
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { Toaster } from "@/components/ui/toaster"



export const metadata: Metadata = {
  title: " آموزش پایتون",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir='rtl'>
      <body className="font-sans">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
            
              <Navbar/>
              <div className=" w:w-[98%] md:w-[90%] mx-auto">

                {children}

              <Toaster />
                
              </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
